package com.centaurstech.sdk;

/**
 * @author Leon(黄长亮)
 * @describe 测试数据
 * @date 2019/6/6
 */
public class TestData {

    public static String trainTicketData = "{\"_ID\":\"221\",\"attitude\":0,\"data\":{\"current_train_index\":\"180\",\"end_city\":\"广州\",\"search_result_type\":3,\"start_city\":\"深圳\",\"trains\":[{\"allSeats\":[{\"name\":\"商务座\",\"number\":13,\"price\":\"199.5\",\"seatClass\":\"businessseat\"},{\"name\":\"一等座\",\"number\":3,\"price\":\"99.5\",\"seatClass\":\"firstseat\"},{\"name\":\"二等座\",\"number\":21,\"price\":\"74.5\",\"seatClass\":\"secondseat\"}],\"arrivaltime\":\"2019-06-07T17:59\",\"costtime\":29,\"departuretime\":\"2019-06-07T17:30\",\"distance\":\"\",\"endstation\":\"广州南\",\"issend\":\"\",\"queryKey\":\"e677bfa46ef03a1079d4721a0b38f2bb\",\"sequenceno\":\"\",\"station\":\"深圳北\",\"trainIndex\":180,\"trainTicket\":{\"middleStation\":0,\"seatClass\":\"secondseat\",\"ticketPrice\":\"74.5\",\"ticketType\":\"二等座\"},\"trainno\":\"G6528\",\"type\":\"高铁\"},{\"allSeats\":[{\"name\":\"商务座\",\"number\":9,\"price\":\"199.5\",\"seatClass\":\"businessseat\"},{\"name\":\"一等座\",\"number\":1,\"price\":\"99.5\",\"seatClass\":\"firstseat\"},{\"name\":\"二等座\",\"number\":21,\"price\":\"74.5\",\"seatClass\":\"secondseat\"}],\"arrivaltime\":\"2019-06-07T18:04\",\"costtime\":29,\"departuretime\":\"2019-06-07T17:35\",\"distance\":\"\",\"endstation\":\"广州南\",\"issend\":\"\",\"queryKey\":\"e677bfa46ef03a1079d4721a0b38f2bb\",\"sequenceno\":\"\",\"station\":\"深圳北\",\"trainIndex\":182,\"trainTicket\":{\"middleStation\":0,\"seatClass\":\"secondseat\",\"ticketPrice\":\"74.5\",\"ticketType\":\"二等座\"},\"trainno\":\"G6512\",\"type\":\"高铁\"}]},\"data_key\":\"d23fe0e4-7d56-44f7-9d44-af99183e788b\",\"expire\":0,\"isNewMsg\":true,\"msgType\":3,\"omit\":false,\"playType\":1,\"showTime\":0,\"sn\":\"751fb5ad-07b5-4bcb-b7da-d721d21474ca\",\"speech\":false,\"state\":0,\"msg\":\" 查到比较合适的是：6月7日17点30分从深圳北站出发，17点59分到达广州南站的G6528次列车，二等座，价格74.5元。 需要帮您预定吗？\",\"retcode\":0,\"timestamp\":1559791258184}\n";
    public static String flightTicketData = "{\"_ID\":\"233\",\"attitude\":0,\"data\":{\"adult_number\":\"1\",\"arrival_city\":\"上海\",\"child_number\":\"0\",\"departure_city\":\"北京\",\"flightTicketInfo\":{\"flightTickets\":[{\"adult_number\":0,\"aircraft\":[\"73U\"],\"arrival_airport\":[\"虹桥机场\"],\"arrival_airport_code\":[\"SHA\"],\"arrival_city\":\"上海\",\"arrival_city_code\":[\"SHA\"],\"arrival_time\":[\"2019-07-01T09:50\"],\"cabin\":[\"Q\"],\"carrier\":[\"联合航空\"],\"carrier_code\":[\"KN\"],\"child_number\":0,\"departure_airport\":[\"南苑机场\"],\"departure_airport_code\":[\"NAY\"],\"departure_city\":\"北京\",\"departure_city_code\":[\"NAY\"],\"departure_time\":[\"2019-07-01T07:50\"],\"duration\":[\"120\"],\"flightTypeFullName\":[\"波音737(中)\"],\"hasBeenTranslated\":false,\"number\":[\"KN5737\"],\"price\":\"487\",\"stop\":false,\"stop_city\":\"\"},{\"adult_number\":0,\"aircraft\":[\"33L\"],\"arrival_airport\":[\"上海虹桥国际机场\"],\"arrival_airport_code\":[\"SHA\"],\"arrival_city\":\"上海\",\"arrival_city_code\":[\"SHA\"],\"arrival_time\":[\"2019-07-01T23:55\"],\"cabin\":[\"T\"],\"carrier\":[\"中国东方航空\"],\"carrier_code\":[\"MU\"],\"child_number\":0,\"departure_airport\":[\"北京首都国际机场\"],\"departure_airport_code\":[\"PEK\"],\"departure_city\":\"北京\",\"departure_city_code\":[\"PEK\"],\"departure_time\":[\"2019-07-01T21:50\"],\"duration\":[\"125\"],\"flightTypeFullName\":[\"空客330/340(宽)\"],\"hasBeenTranslated\":true,\"number\":[\"MU5160\"],\"price\":\"517\",\"stop\":false,\"stop_city\":\"\"}],\"mid\":\"233\",\"return_trip\":false,\"selectPosition\":0,\"stage\":\"FIRST\"},\"return_trip\":\"false\",\"search_result_type\":2,\"stage\":\"FIRST\"},\"data_key\":\"251bf134-455b-4abb-bdb8-817f7c954797\",\"expire\":0,\"isNewMsg\":true,\"msgType\":2,\"omit\":false,\"playType\":1,\"showTime\":0,\"sn\":\"5a29ff8e-8170-46fe-953d-84159e38acd8\",\"speech\":false,\"state\":0,\"msg\":\"查到110个航班，比较合适的是经济舱单价约487元，07月01日 7点50分从北京南苑机场出发， 9点50分到达上海虹桥机场，联合航空 KN5737次航班， 要订这张票吗？\",\"retcode\":0,\"timestamp\":1560131691419}\n";
    public static String passengers = "";


}
